apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitdocs.fullname" . }}
  labels:
    {{- include "gitdocs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.internalServicePort }}
  selector:
    {{- include "gitdocs.selectorLabels" . | nindent 4 }}
