apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitdocs
spec:
  template:
    spec:
      containers:
      - name: git-sync
        env:
        - name: GIT_SYNC_REPO
          value: "https://github.com/google/docsy-example.git"
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEPTH
          value: "1"
      - name: hugo
        # https://github.com/google/docsy-example/blob/master/netlify.toml
        image: klakegg/hugo:0.104.3-ext-alpine
